apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: nginx-svc
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.99.125
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: sshd
    port: 22
    targetPort: 22

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
      app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-web4
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: nginx-http
        - containerPort: 443
          name: nginx-https
        - containerPort: 22
          name: nginx-sshd
