apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: phpmyadmin-deploy
    labels:
      app: phpmyadmin
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: phpmyadmin
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: phpmyadmin
      spec:
        containers:
        - name: phpmyadmin
          image: phpmyadmin-web3
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
  
