apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegraf-pvc
  labels:
    type: local
spec:
  storageClassName: telegraf-pvc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/docker.sock"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegraf-pvc
  labels:
    app: telegraf
spec:
  storageClassName: telegraf-pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf-web
          name: telegraf
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
              readOnly: true
            - name: telegraf-pvc
              mountPath: "/var/run/docker.sock"
          envFrom:
            - secretRef:
                name: telegraf-secrets
      volumes:
        - name: telegraf-pvc
          persistentVolumeClaim:
            claimName: telegraf-pvc
        - name: telegraf-config
          configMap:
            name: telegraf-config
